version: '3'
networks:
  percona:
    external: false
  server:
    external: false
  prometheus:
    external: false
volumes:
  prometheus:
    driver: local
  grafana-lib:
    driver: local
  grafana-log:
    driver: local
  percona:
    driver: local
services:
  percona:
    image: percona/percona-server@sha256:ad0f73c99b004074c2e8555c5229d247e95df8a9f7c0f0433d73bc86881f13d9 # percona/percona-server:8.0.26
    environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=nonroot
    - MYSQL_PASSWORD=nonroot
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - percona
    ports:
    - '127.0.0.1:3306:3306'
    volumes:
    - percona:/var/lib/mysql

  server-percona-schema:
    build:
      context: ./../..
      dockerfile: ./scripts/docker/schema/Dockerfile
    command:
    - up
    environment:
    - PERCONA_DSN=mysql://root:root@tcp(percona:3306)/db
    networks:
    - percona
    depends_on:
    - percona

  server-swagger:
    build:
      context: ./../..
      dockerfile: ./scripts/docker/swagger/Dockerfile
    ports:
    - '127.0.0.1:8081:8080'

  server:
    restart: on-failure
    build:
      context: ./../..
      dockerfile: ./scripts/docker/server/Dockerfile
    environment:
    - SERVER_HTTP_ADDRESS=0.0.0.0:8080
    - SERVER_MONITOR_ADDRESS=0.0.0.0:9090
    - SERVER_PERCONA_DSN=nonroot:nonroot@tcp(percona:3306)/db
    - SERVER_LOG_LEVEL=debug
    - SERVER_BASE_URL=http://127.0.0.1:8080
    networks:
    - server
    - percona
    ports:
    - '127.0.0.1:8080:8080'
    depends_on:
    - percona

  prometheus:
    image: prom/prometheus@sha256:f2fa04806b65f49b652c8d418544bb9660bb8224619ee8c960a778f46614dddf # prom/prometheus:v2.36.2
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
    - prometheus:/prometheus
    - ./prometheus:/etc/prometheus:ro
    networks:
    - prometheus
    - server

  grafana:
    image: grafana/grafana@sha256:1e180fcaede581b8cc8e2ce8bc010daff9c64972023a0faaf226d92bd9840113 # grafana/grafana:9.0.2
    volumes:
    - grafana-lib:/var/lib/grafana
    - grafana-log:/var/log/grafana
    - ./grafana:/etc/grafana/provisioning:ro
    networks:
    - prometheus
    ports:
    - '127.0.0.1:3000:3000'
    depends_on:
    - prometheus
